version: "3.4"

services:
  app:
    container_name: thehivehook_go.gcm-test
    environment:
      - GO_HIVEHOOK_THAPIKEY=$HIVEHOOK_THAPIKEY
      - GO_HIVEHOOK_DBWLOGPASSWD=$HIVEHOOK_DBWLOGPASSWD
    image: gitlab.cloud.gcm:5050/a.belyakov/thehivehook_go_package:test
    restart: unless-stopped
    #пробрасываем user ID для корректной записи логов
    user: root
    command: chmod 777 /opt/thehivehook_go_package/logs && \
             chown 1500:1500 /opt/thehivehook_go_package/logs
    volumes:
      - /var/log/thehivehook_go_package.gcm-test:/opt/thehivehook_go_package/logs:rw
      - ./config:/opt/thehivehook_go_package/config:rw
      #для корректного отображения даты с учетом временной зоны
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
