COMMONINFO:
  file_name: "config_prod"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    sender_case: "object.casetype"
    sender_alert: "object.alerttype"
    listener_command: "object.commandstype"
THEHIVE:
  host: "thehive.cloud.gcm"
  port: 9000
  cacheTtl: 43200
WEBHOOKSERVER:
  name: "gcm"
  host: "192.168.13.3"
  port: 5000
  ttlTmpInfo: 10
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  namedb: ""
  storageNamedb: "thehivehook_go_package"
  user: "log_writer"
