LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000000,
      writingDB: true,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000000,
      writingDB: true,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 10000000,
      writingDB: false,
    }
  - {
      msgTypeName: "log_to_db",
      writingFile: false,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 30000000,
      writingDB: true,
    }
  - {
      msgTypeName: "log_for_test",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: false,
      maxFileSize: 1000000,
      writingDB: false,
    }
ZABBIX:
  networkHost: "192.168.9.45"
  networkPort: 10051
  zabbixHost: "test-uchet-db.cloud.gcm"
  eventTypes:
    # для отслеживания ошибок
    - eventType: "error"
      zabbixKey: "shaper_stix.error"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: ""
    # для информационных сообщений о выполненной работе
    - eventType: "info"
      zabbixKey: "shaper_stix.info"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: "I'm still alive"
    # для регулярного отстукивания что модуль еще работает
    - eventType: "handshake"
      zabbixKey: "shaper_stix.handshake"
      isTransmit: true
      handshake:
        timeInterval: 1
        message: "0"
