COMMONINFO:
  file_name: "config_dev"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cache_ttl: 3600
  subscriptions:
    sender_case: "object.casetype"
    sender_alert: "object.alerttype"
    listener_command: "object.commandstype"
THEHIVE:
  host: "thehive.cloud.gcm"
  port: 9001
  cache_ttl: 3600
WEBHOOKSERVER:
  name: "rcmsml"
  host: "127.0.0.1"
  port: 5000
  ttl_tmp_info: 12
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  namedb: "nameDB"
  storage_name_db: "thehivehook_go_package"
  user: "log_writer"
