COMMONINFO:
  file_name: "config_dev"
NATS:
  prefix: "test"
  host: "192.168.9.208"
  port: 4222
  cache_ttl: 3600
  subscriptions:
    sender_case: "object.casetype.test"
    sender_alert: "object.alerttype.test"
    listener_command: "object.commandstype.test"
THEHIVE:
  host: "thehive.cloud.gcm"
  port: 9001
  cache_ttl: 3600
WEBHOOKSERVER:
  name: "gcm-test"
  host: "192.168.9.208"
  port: 5000
  ttl_tmp_info: 12
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  namedb: "nameDB"
  storage_name_db: "thehivehook_go_package"
  user: "log_writer"
