COMMONINFO:
  file_name: config_development
TEMPORARYSTORAGE:
  storage_object_ttl: 180
  storage_delay_to_send_alert: 5
  storage_delay_to_send_case: 30
NATS:
  host: 192.168.9.208
  port: 4222
  subscriptions:
    sender_case: object.casetype.test
    sender_alert: object.alerttype.test
    listener_command: object.commandstype.test
THEHIVE:
  host: thehive.cloud.gcm
  port: 9000
  cache_ttl: 43200
WEBHOOKSERVER:
  name: gcm-dev-test
  host: 192.168.9.208
  port: 5000
DATABASEWRITELOG:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: thehivehook_go_package
