COMMONINFO:
  file_name: "config production"
TEMPORARYSTORAGE:
  storage_object_ttl: 180
  storage_delay_to_send_alert: 5
  storage_delay_to_send_case: 30
NATS:
  host: nats.cloud.gcm
  port: 4222
  subscriptions:
    sender_case: object.casetype
    sender_alert: object.alerttype
    listener_command: object.commandstype
THEHIVE:
  host: thehive.cloud.gcm
  port: 9000
WEBHOOKSERVER:
  name: gcm
  host: 192.168.9.53
  port: 5001
DATABASEWRITELOG:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: thehivehook_go_package
