COMMONINFO:
  file_name: "config_dev"
NATS:
  host: "nats.cloud.gcmtest"
  port: 4223
  subscribers:
    - event: "caseupdate"
      responders:
        - "ATD"
        - "ES"
        - "MISP"
        - "MISP_TEST"
        - "NCIRCC"
    - event: "alertupdate"
      responders:
        - "ES"
        - "MISP"
        - "NCIRCC"
THEHIVE:
  host: "thehive.cloud.gcm"
  port: 9001
WEBHOOKSERVER:
  name: "rcmsml"
  host: "127.0.0.1"
  port: 5000
  ttlTmpInfo: 12
SQLITE:
  pathDatabase: "../../../../../_sqlite/database/db.sqlite"
