COMMONINFO:
  file_name: "config_prod"
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  subscribers:
    - event: "caseupdate"
      responders:
        - "ATD"
        - "ES"
        - "MISP"
        - "MISP_TEST"
        - "NCIRCC"
    - event: "alertupdate"
      responders:
        - "ES"
THEHIVE:
  host: "192.168.42.10"
  port: 9000
ELASTICSEARCH:
  host: "datahook.cloud.gcm"
  port: 9200
  user: "writer"
  prefix: ""
  index: "thehivehook_go_package"
HOOKSERVER:
  host: "192.168.13.3"
  port: 7878
