COMMONINFO:
  file_name: "config_dev"
NATS:
  host: "nats.cloud.gcmtest"
  port: 4223
  subscribers:
    - event: "caseupdate"
      responders:
        - "ATD"
        - "ES"
        - "MISP"
        - "MISP_TEST"
        - "NCIRCC"
    - event: "alertupdate"
      responders:
        - "ES"
        - "MISP"
        - "NCIRCC"
THEHIVE:
  host: "192.168.42.10"
  port: 9001
ELASTICSEARCH:
  host: "datahook.cloud.gcm"
  port: 9200
  user: "writer"
  prefix: "test_"
  index: "thehivehook_go_package"
HOOKSERVER:
  host: "127.0.0.1"
  port: 7878
