LOGGING:
  - {
      msgTypeName: "error",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 1000000,
    }
  - {
      msgTypeName: "warning",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 1000000,
    }
  - {
      msgTypeName: "info",
      writingFile: true,
      pathDirectory: "logs",
      writingStdout: true,
      maxFileSize: 1000000,
    }
ZABBIX:
  networkHost: "192.168.9.45"
  networkPort: 10051
  zabbixHost: "test-uchet-db.cloud.gcm"
  eventTypes:
    # для отслеживания ошибок
    - eventType: "error"
      zabbixKey: "shaper_stix.error"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: ""
    # для информационных сообщений о выполненной работе
    - eventType: "info"
      zabbixKey: "shaper_stix.info"
      isTransmit: true
      handshake:
        timeInterval: 0
        message: "I'm still alive"
    # для регулярного отстукивания что модуль еще работает
    - eventType: "handshake"
      zabbixKey: "shaper_stix.handshake"
      isTransmit: true
      handshake:
        timeInterval: 1
        message: "0"
