COMMONINFO:
  file_name: "config_prod"
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  subscribers:
    - event: "caseupdate"
      responders:
        - "gcm"
        - "rcmmsk"
        - "rcmnvs"
    - event: "alertupdate"
      responders:
        - "gcm"
THEHIVE:
  host: "192.168.42.10"
  port: 9000
  user_name: "test"
ELASTICSEARCH:
  host: "datahook.cloud.gcm"
  port: 9200
  user: "writer"
  prefix: ""
  index: "thehivehook_go_package"
HOOKSERVER:
  host: "192.168.13.3"
  port: 7878
