COMMONINFO:
  file_name: "config_dev"
NATS:
  host: "nats.cloud.gcmtest"
  port: 4223
  subject_case: "main_caseupdate_test"
  subject_alert: "main_alertupdate_test"
THEHIVE:
  host: "192.168.42.10"
  port: 9001
  user_name: "testtest"
