COMMONINFO:
  file_name: "config_prod"
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 43200
  subscribers:
    - event: "caseupdate"
      responders:
        - "ATD"
        - "ES"
        - "MISP"
        - "MISP_TEST"
        - "NCIRCC"
    - event: "alertupdate"
      responders:
        - "ES"
THEHIVE:
  host: "thehive.cloud.gcm"
  port: 9000
  cacheTtl: 43200
WEBHOOKSERVER:
  name: "gcm"
  host: "192.168.13.3"
  port: 5000
  ttlTmpInfo: 10
