COMMONINFO:
  file_name: "config_prod"
NATS:
  host: "nats.cloud.gcm"
  port: 4222
  subject_case: "main_caseupdate"
  subject_alert: "main_alertupdate"
THEHIVE:
  host: "192.168.42.10"
  port: 9000
  user_name: "test"
